version: "3.9"
services:
  app_api:
    build:
      context: ./app_api
    ports:
      - "8000:8000"
    environment:
      - DATA_API_URL=http://data_api:9000
      - PYTHONPATH=/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db

  data_api:
    build:
      context: ./data_api
    ports:
      - "9000:9000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - RUN_TESTS=1 
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 9000

volumes:
  mongodb_data:
